# Generated by Django 4.1.4 on 2022-12-15 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('marketplace_app', '0002_alter_product_sku'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='SKU',
            field=models.CharField(default='AD8UYP0', editable=False, max_length=50),
        ),
    ]
